### ISSUE TITLE
How you merge and rebase without fugitive?

### ISSUE THREAD

**Issue by fragov** [davidosomething/dotfiles#275]
Hi, sorry to bother you, but may you tell me, why you do not use vim-fugitive from tpope? How you make merge and rebase?

**Comment by davidosomething** [comment]
I use git from the command line
Doing it from within vim and masked behind vim commands is actually much more cumbersome

to merge one branch into another is as simple as `git merge a b`
to rebase, it's just `git rebase branch` or `git rebase -i ref` to interactively squash

my git editor is set to vim, so i can edit commit messages and interact with rebase in vim, but no need to add files to stage/unstage there.
