### ISSUE TITLE
I extracted MRU fzf to a plugin

### ISSUE THREAD

**Issue by stagnation** [davidosomething/dotfiles#75]
https://github.com/stagnation/nilsvim_fzf

Based on "[...] but check out my dotfiles repo if you want to de-construct it for yourself." I assumed that you don't mind. Do you object? I might add more functionality from digging through your fzf code.

I couldn't find any repos on your github from this: https://github.com/davidosomething/dotfiles/issues/19
split vim fzf stuff into separate vim repo plugins #19

Best,
Nils

**Comment by davidosomething** [comment]
sure, go at it
